services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./db:/data/db # Map to host folder
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - BASE_URL=prodURL
      - EXPECTED_USER=changeme
      - EXPECTED_KEY=changeme
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB_NAME=farnsworth
    depends_on:
      - mongodb
    volumes:
      - ./media:/media # Map to host folder