services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./db:/data/db # Map to host folder
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_URL=prodURL
    ports:
      - "8080:8080" #probably change this
    environment:
      - EXPECTED_USER=changeme
      - EXPECTED_KEY=changeme
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB_NAME=farnsworth
    depends_on:
      - mongodb
    volumes:
      - ./media:/app/media # keep things where you can see em
      - ./logs:/app/logs 
      - ./chunks:/app/chunks #easier to cleanup failed uploads this way
